---
- name: Establecer permisos de directorio home
  file:
    path: "~"
    mode: '0710'

- name: Crear directorio ~/.mpd/playlists
  file:
    path: "~/.mpd/playlists"
    state: directory
    mode: '0777'

- name: Copiar configuraci√≥n de MPD para usuario
  copy:
    src: "mpd.conf"
    dest: "~/.mpd/mpd.conf"
    mode: '0644'

- name: Habilitar mpd como servicio de usuario para alex
  systemd:
    name: mpd.service
    scope: user
    enabled: true
    daemon_reload: true
    state: started
